#!/bin/sh
function git_diff_archive()
{
  local diff=""
  local name="archive"
  local h="HEAD"
  local start=""
  local end=""
  local root=""
  local dir=""
  local date=`date +%y%m%d`
  if [ $# -eq 1 ]; then
    name="$1"
    root="$1"
  elif [ $# -eq 2 ]; then
    name="$1"
    root="$1"
    if expr "$2" : '[0-9]*$' > /dev/null ; then
      diff="HEAD~${2} HEAD"
    else
      diff="${2} HEAD"
    fi
  elif [ $# -eq 3 ]; then
    name="$1"
    root="$1"
    if expr "$2" : '[0-9]*$' > /dev/null ; then
      start="HEAD~${2}"
    else
      start="$2"
    fi
    if expr "$3" : '[0-9]*$' > /dev/null ; then
      end="HEAD~${3}"
    else
      end="$3"
    fi
    h=$end
    diff="${start} ${end}"
  elif [ $# -eq 4 ]; then
    name="$1"
    if expr "$2" : '[0-9]*$' > /dev/null ; then
      start="HEAD~${2}"
    else
      start="$2"
    fi
    if expr "$3" : '[0-9]*$' > /dev/null ; then
      end="HEAD~${3}"
    else
      end="$3"
    fi
    if expr "$4" : '^:' > /dev/null ; then
      dir="$4"
      root="$1"
    else
      dir=""
      root="$4"
    fi
    h="${end}${dir}"
    diff="${start}${dir} ${end}${dir}"
  elif [ $# -eq 5 ]; then
    name="$1"
    dir="$4"
    root="$5"
    if expr "$2" : '[0-9]*$' > /dev/null ; then
      start="HEAD~${2}"
    else
      start="$2"
    fi
    if expr "$3" : '[0-9]*$' > /dev/null ; then
      end="HEAD~${3}"
    else
      end="$3"
    fi
    h="${end}${dir}"
    diff="${start}${dir} ${end}${dir}"
  fi
  if [ "$diff" != "" ]; then
    diff="git diff --diff-filter=d --name-only ${diff}"
  fi
  git archive --format=zip --prefix=$root/ $h `eval $diff` --worktree-attributes -o ~/desktop/${date}_${name}_data.zip
}
